# Site settings
title: x64dbg
description: "An open-source x64/x32 debugger for windows."
baseurl: "/x64dbg.github.io"
url: "http://www.x64dbg.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
